import type { ConversationType, Level, NormalizedConversation, Candidate } from '../types';
import { renderCoding } from '../templates/coding';
import { renderMixed } from '../templates/mixed';
import { renderPlanning } from '../templates/planning';
import { renderResearch } from '../templates/research';
import { renderWriting } from '../templates/writing';
import {
  buildContext,
  buildFooter,
  buildGoal,
  buildHeader,
  buildNextSteps,
  type RenderContext,
} from '../templates/universal';
import {
  renderAttachmentPlaceholder,
  renderInlineCodeFile,
  shouldInlineCodeFile,
} from '../utils/attachments';

export function render(
  conv: NormalizedConversation,
  type: ConversationType,
  selected: Candidate[],
  level: Level,
  stats: { input: number; output: number }
): string {
  if (level === 'full') return renderFull(conv, stats);
  if (level === 'tldr') return renderTldr({ conv, type, level, selected }, stats);

  const ctx: RenderContext = { conv, type, level, selected };
  switch (type) {
    case 'coding': return renderCoding(ctx, stats);
    case 'writing': return renderWriting(ctx, stats);
    case 'research': return renderResearch(ctx, stats);
    case 'planning': return renderPlanning(ctx, stats);
    case 'mixed': return renderMixed(ctx, stats);
  }
}

function renderTldr(ctx: RenderContext, stats: { input: number; output: number }): string {
  return [
    buildHeader(ctx, stats),
    buildContext(ctx),
    buildGoal(ctx),
    buildNextSteps(ctx),
    buildFooter(),
  ]
    .filter(Boolean)
    .join('\n\n') + '\n';
}

function renderFull(conv: NormalizedConversation, stats: { input: number; output: number }): string {
  const title = conv.title?.trim() || 'Conversation';
  const head = `# ${title}\n\n**Source:** ${conv.source}\n`;
  const body: string[] = [];

  if (conv.systemPrompt) {
    body.push(`## System\n${conv.systemPrompt}`);
  }

  for (const m of conv.messages) {
    const heading = m.role === 'user' ? '### User' : m.role === 'assistant' ? '### Assistant' : `### ${m.role}`;
    const parts: string[] = [heading];

    for (const b of m.content) {
      if (b.type === 'text') parts.push(b.text);
      else if (b.type === 'code') parts.push(`\`\`\`${b.language ?? ''}\n${b.text}\n\`\`\``);
      else if (b.type === 'artifact') {
        parts.push(`**Artifact: ${b.title}**\n\n\`\`\`${b.language ?? ''}\n${b.text}\n\`\`\``);
      }
    }

    for (const a of m.attachments) {
      parts.push(shouldInlineCodeFile(a) ? renderInlineCodeFile(a) : renderAttachmentPlaceholder(a));
    }
    body.push(parts.join('\n\n'));
  }

  const footer = `---\n*Generated by ChatPort. Compressed ${stats.input.toLocaleString()} → ${stats.output.toLocaleString()} chars.*`;
  return [head, ...body, footer].join('\n\n') + '\n';
}
